### ISSUE TITLE
[Feature Request] Be able to display point from url

### ISSUE THREAD

**Issue by LukyVj** [jeanropke/RDOMap#100]
Hello and thanks for taking care of this project! 

I was wondering if you guys would like to implement a feature that would check url parameters and display the corresponding point on the map. 

I was thinking that you could explore a similar solution as this one, when the page loads: 
for the url `https://jeanropke.github.io/RDOMap?item=mp_animal_cougar_legendary_02`

```javascript
const item = window.location.search.split('?item=')[1] // mp_animal_cougar_legendary_02

// Feed the script with this item as item to display
```

Let me know what you think. 
Happy to chime in and propose a PR.

**Comment by Senexis** [comment]
https://jeanropke.github.io/RDOMap/?q=mp_animal_cougar_legendary_02 :)

**Comment by LukyVj** [comment]
Dude, you rock <3

**Comment by LukyVj** [comment]
Thanks a lot for being so fast!

**Comment by Senexis** [comment]
I was already using this for the bot. Works on any key, including events etc. 😊

**Comment by LukyVj** [comment]
Okay, that's really awesome, I'm working on RDR project and wanted to redirect people to This map! So that's extremely helpful! You guys are making an impressive work! 

RDR2Tax: I'm the author of madamnazar.io !

**Comment by Senexis** [comment]
I know haha, happy to help.

**Comment by LukyVj** [comment]
Hey, what's the query for regular animals? 

I'm trying to pass their thumbnail names, for example: `MP_ANIMAL_COW` lowercased, giving me this url: https://jeanropke.github.io/RDOMap/?q=mp_animal_cow

But it doesn't seem to work as intended. Is it only for legendary?

**Comment by Senexis** [comment]
Only the keys that are available in the map work, so for cows that would be https://jeanropke.github.io/RDOMap/?q=animal_cow.

**Comment by LukyVj** [comment]
Right, I see :) Thanks mate. 

Lastly, it would be nice to have a parameter to control the zoom in/out, like `z=0.5` :D 
My 2 cents
