### ISSUE TITLE
Important legendary cogi coar translate error in spanish

### ISSUE THREAD

**Issue by Njordude** [jeanropke/RDOMap#102]
![error de traduccion](https://user-images.githubusercontent.com/70353928/91508273-0a672080-e8a5-11ea-93f1-6e6d298996bb.png)
![error de traduccion 2](https://user-images.githubusercontent.com/70353928/91508279-0dfaa780-e8a5-11ea-8c41-3834b04ead24.jpeg)

In RDO Map says "Esta subespecie suele pastar al _amanecer_ y prefiere el clima seco." when in game, the animal guide says "Esta subespecie suele pastar al _atardecer_ y prefiere el clima seco." i suppose is worth mentioning this because the spawn time for legendary animals must be right in RDO Map to avoid wasting time searching for some random animal in the wrong time frame.

**Comment by MichalD96** [comment]
Hey, good you noticed that. You con correct every translation by your own here: https://crowdin.com/project/rdr2rdomap

**Comment by Njordude** [comment]
Actually i changed it after i realized that what was in RDO map was right and the translation in the game itself was mistaken (America Latina) so i submitted a ticket in rockstar support to let them know about this. i came to this conclusion after watching some videos about the boar in YT, in all of them is said that the boar spawns from 6am to 9am which is morning or dawn of course so the original translate was right and mine was not, so cause of this i deleted mine and voted the previous one. btw thanks for giving me the link to help w the spanish translations, ill be happy to help with the most i can :)
