### ISSUE TITLE
Treasure maps on trees...

### ISSUE THREAD

**Issue by TheBlackWitch** [jeanropke/RDOMap#103]
I am curious as to why you took down the list of trees that can randomly spawn treasure maps..?  I have most of them memorized and took a map from in RIO on the tree in the lightning patch, the tree outside thieves landing, and the tree near stillwater creek.  I would love to see it go back up.  Thanks for all your hard work.

**Comment by MichalD96** [comment]
Treasure maps on trees have never been removed from the map. Go to `Random Encounters` category => `Treasure map on tree`
https://jeanropke.github.io/RDOMap/?q=tree_map
