### ISSUE TITLE
Preferred time/weather for Legendary Animals on RDO map

### ISSUE THREAD

**Issue by TheDutchDemon** [jeanropke/RDOMap#105]
**Is your feature request related to a problem? Please describe.**
The Red Dead Online discord, found here: https://discord.gg/3zt495X has a channel called "compendium" where a bot can, among other things, list the exact preferred times and weather for specific legendary animals. Currently, the map simply states "morning, day, night, etc"

**Describe the solution you'd like**
If you could take a look at how the information is presented through the bot on that discord, I would find it immensely more useful if I could check the map at a glance and see exact times rather than an estimate.

**Describe alternatives you've considered**
N/A

**Additional context**
If you decide to experiment with the bot to see what I mean simple type "!f (insert animal/legendary name/just about anything else here)"

**Comment by Senexis** [comment]
Hey there, the bot's developer here. Might as well add this to the map too. Thanks for using the bot!

**Comment by MichalD96** [comment]
I added it to the marker popups
![Zrzut ekranu 2020-10-27 112104](https://user-images.githubusercontent.com/53737762/97288721-8dc1d580-1846-11eb-9559-8e1a68ab06a3.png)
