### ISSUE TITLE
Legendary animal prices

### ISSUE THREAD

**Issue by QuinnLion** [jeanropke/RDOMap#106]
Please consider adding prices to the maps to show how much you'd get if sold to Gus.

Attached is spreadsheet of prices.  I have no idea if they change or not with the exception of promoted Legendaries.

[Gus price list.xlsx](https://github.com/jeanropke/RDOMap/files/5337670/Gus.price.list.xlsx)

**Comment by MichalD96** [comment]
Added to both maps:
![Zrzut ekranu 2020-10-07 051830](https://user-images.githubusercontent.com/53737762/95283627-8d907480-085c-11eb-94da-e318e181caf9.png)
