### ISSUE TITLE
Daily Challenges Not Showing

### ISSUE THREAD

**Issue by gold007eye** [jeanropke/RDOMap#107]
For the past few days now I am not able to see the daily challenges.  I have tried this on 2 different computers with the same results.  I have also tried removing any cookies for the site, reloading the map, and also Reset All Settings on the map to no avail.

Browser is FireFox, but I also just tried it on Edge browser (that I have never been to the site before on with the same results).

Here is the error I am seeing:
![image](https://user-images.githubusercontent.com/4365462/96877978-eefd3980-143f-11eb-9801-44359c1ec0b5.png)

**Comment by MichalD96** [comment]
yes, we know about it, we have problem with the server, already working to fix it.
Dailies, madam nazar location, and weekly set are unavailable now

**Comment by gold007eye** [comment]
Ok I feel better knowing it wasn't just me.  I noticed the same thing with Madam Nazar yesterday, but thought maybe I was just missing it, but on her issue I also noticed at the same time she hasn't been showing up in-game either until I switch lobbies a few times or collect a few collectables then she magically appears in-game (not sure if that is affecting your map.)

**Comment by MichalD96** [comment]
Fixed

**Comment by Duemos735** [comment]
It's still happening.
