### ISSUE TITLE
Single player 

### ISSUE THREAD

**Issue by jonnyhardcore1** [jeanropke/RDOMap#113]
None of the single player stuff is showing up on the rdmap like dinosaurs bones, dream catchers, etc . Iam clicking on them but when I go to the map nothing is on it

**Comment by MichalD96** [comment]
That is iconography, not the markers. Iconography is the text or icons on the map that appears on high zoom lvl like this:
![Zrzut_ekranu_2020-11-07_000844](https://user-images.githubusercontent.com/53737762/106367433-ed96b380-6342-11eb-8d88-95a7eaf29979.png)
