### ISSUE TITLE
Add ability to hide pin types by clicking on them

### ISSUE THREAD

**Issue by bogosj** [jeanropke/RDOMap#115]
Rather than have to scroll through the left bar to find the "Wintergreen Berry" toggle, or "Dog Encounter", it would be nice if when you clicked on a pin the tooltip that popped up had a link/button inside of it that said "hide all pins of this type" or something similar.

**Comment by MichalD96** [comment]
Added

**Comment by bogosj** [comment]
Amazing turn around. Thank you!
