### ISSUE TITLE
Entire map not loading up on safari for new ipad

### ISSUE THREAD

**Issue by CaptainSlugwhisker** [jeanropke/RDOMap#118]
https://user-images.githubusercontent.com/87246520/125177232-1485cb00-e1a8-11eb-8409-041ac4f8233b.MP4

Reloaded, closed, exited all safari apps, restarted ipad many times.
Been going on for about 2days almost. 
ty for help

**Comment by MichalD96** [comment]
Try to open the map from this link: https://jeanropke.github.io/RDOMap/?show-alert=1
and send me screenshot of the alert message that pop up after the map open. 
Last major change in map code i made around 2 weeks ago, so it is problem with something else than the map code.
You can also scroll in menu and click "Reset all settings" button, that should reload everything - very often help.

**Comment by CaptainSlugwhisker** [comment]
Thank you 🙏🏼 here is screenshot. I will try the reset all settings too and let you know if not resolved. 🤞🏽
![Uploading 1A16A170-DBAA-419B-94FC-4234AEC42CE6.png…]()

**Comment by CaptainSlugwhisker** [comment]
Fixed with your suggestion! Ty ty ty 💋
