### ISSUE TITLE
Roads missing

### ISSUE THREAD

**Issue by rijames77** [jeanropke/RDOMap#120]
In the past several weeks I've noticed quite a few of the secondary and all the tertiary roads are missing from the map

**Comment by Pablo-Diablo** [comment]
Not only that, but all existing roads are the same color as the rest map details making it difficult to navigate. They  have to be darker just like in game.

**Comment by MichalD96** [comment]
You can use detailed map that is exactly the same as map in game,
and also i recommend to read map Wiki page [here](https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide#basic-map-functionality), that should solve both your problems.

**Comment by rijames77** [comment]
Outstanding! Don't know how my map changed it's settings but thanks!
-------- Original message --------From: Michal__d ***@***.***> Date: 8/22/21  13:51  (GMT-05:00) To: jeanropke/RDOMap ***@***.***> Cc: rijames77 ***@***.***>, Author ***@***.***> Subject: Re: [jeanropke/RDOMap] Roads missing (#120) 
You can use detailed map that is exactly the same as map in game,
and also i recommend to read map Wiki page here, that should solve both your problems.
