### ISSUE TITLE
Incorrect Daily challenges for roles

### ISSUE THREAD

**Issue by SixianOne** [jeanropke/RDOMap#121]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

I use the map almost every day and the General daily challenges are always correct. But the roles challenges are always different from the challenges in the game.
Is it a bug or am I doing something wrong?

**Comment by MichalD96** [comment]
It is not a bug. All role challenges displayed on the map are for role rank 15+
You need at least 15 role rank to get this dailies. Note that role rank is not your game level.
[This site](https://rdodailies.com/), can show you all dailies for all ranks.

**Comment by SixianOne** [comment]
Thank you
