### ISSUE TITLE
Incorrect item Cycle: day #  daily challenges not showing

### ISSUE THREAD

**Issue by dist6chair** [jeanropke/RDOMap#132]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MoffCH** [comment]
Jan 3rd 1:20 pm Pacific Wild Flowers Cycle 4 Arrowhead Cycle 6.  Looked at Midnight game time and no flower.  No other flowers at their spawn points.  None of the random locations seem to match up.  I have both Metal Detector and shovel.  Most Cards are correctly located.  Ebony hairpin appears missing.
![EbonyHairpin](https://github.com/jeanropke/RDOMap/assets/2709224/6becba20-596d-46e5-b0fd-ebef372dd950)

![PlantArrowheadIncorrect](https://github.com/jeanropke/RDOMap/assets/2709224/60b58a71-ac6e-429c-ac14-552641f0b818)

**Comment by MoffCH** [comment]
Never mind, some kinda R* bug.  Many collectables were unfindable even with a map, possibly due to snow.  Started working today.
