### ISSUE TITLE
Black screen on map zoom

### ISSUE THREAD

**Issue by Jo-Saiyan** [jeanropke/RDOMap#136]
Whenever you go to zoom in or out the map glitches and makes the whole map black

**Comment by MichalD96** [comment]
Is it desktop or mobile? If mobile, android or something else? Which browser? What are your map settings, you can post exported .json file here.
If you are not on moblie, click F12, go to "Console" tab and make screenshot of everything what is there.

**Comment by Jo-Saiyan** [comment]
I’m on mobile. On Jul 5, 2023, at 18:56, Michal__d ***@***.***> wrote:﻿
Is it desktop or mobile? If mobile, android or something else? Which browser? What are your map settings, you can post exported .json file here.
If you are not on moblie, click F12, go to "Console" tab and make screenshot of everything what is there.

**Comment by MichalD96** [comment]
Could you reply to the rest of my questions, not just first one?
