### ISSUE TITLE
Plants menu not working

### ISSUE THREAD

**Issue by Techman719** [jeanropke/RDOMap#142]
I can open the plants drop-down but can't select any items. All other drop-downs work just fine.

**Comment by MichalD96** [comment]
What is your OS, browser, browser version, can you see any error in the console when you press F12? If you see the error, post a screenshot of the whole browser window here.
Have you tried to use map on another browser (if yes, what browser and is the problem persists)?
Have you tried to revert map to default settings by "Reset all settings" option in menu?

**Comment by Techman719** [comment]
windows 10 Home (22H2),  Firefox 128.0 64 bit
I didn't try a different browser.
I did reset about two weeks ago. While typing this I did do a reset of the
map and now it works fine. Sorry that I wasted your time like that. I
thought it was a bug, not a setting.

**Comment by MichalD96** [comment]
No worries. I am glad it works again. 8 days ago i changed plants menu behavior, and in some specific cases it caused that bug. Your map were using old setting instead of new one. Settings reset just deleted old value that caused the issue.
