### ISSUE TITLE
12/23 daily challenges on map are incorrect

### ISSUE THREAD

**Issue by Oracle59** [jeanropke/RDOMap#152]
**Is your feature request related to a problem? Please describe.**
Daily challenges listed on map are different than listed in the game

**Describe the solution you'd like**
Would like them to match

**Comment by MichalD96** [comment]
Your role challenges are different because your in game role rank is lower than 15.
You need to adjust that setting:
![image](https://github.com/user-attachments/assets/10141181-f62d-4faa-b8f2-c572e80f908d)

**Comment by Oracle59** [comment]
That is incorrect. I am ranked 20 a naturalist collector, bounty, hunter
and trader. None of the daily challenges on those rolls are on the map for
level 15+.

**Comment by MichalD96** [comment]
Which browser do you use? Is it an issue every day or that is first time?
Try to refresh map by ctrl + F5
