### ISSUE TITLE
Spainish Translation

### ISSUE THREAD

**Issue by BurakkuH0ku** [jeanropke/RDOMap#24]
Hello , can i help to translate RDO Markers map for Spainish user ???

**Comment by jeanropke** [comment]
Yes, fork the project, create a copy of 'en-us.json', rename to 'es-es.json'. When is done, open a pull request.

**Comment by BurakkuH0ku** [comment]
Hello i just finished it.

**Comment by BurakkuH0ku** [comment]
I hope I did it well

**Comment by jeanropke** [comment]
Merge approved
