### ISSUE TITLE
Accurate Timing:

### ISSUE THREAD

**Issue by PresidentEkhart** [jeanropke/RDOMap#43]
**Is your feature request related to a problem? Please describe.**
I have built an RP Crew on Red Dead that is thriving. However, the one thing that we are missing is the ability to predict WHEN the Gang Hideouts, rescue missions, etc., spawn in online. We understand that you have their locations marked, but is there a way for your map to act as a live indicator of when these events are active in online?

**Describe the solution you'd like**
We would like map to act as a live indicator of WHEN gang hideouts, rescue missions, etc., are active online.

Thank you for your interactive map. I just hope that you can make it live.

**Comment by jeanropke** [comment]
Not possible. This events are random. Some gang hideouts has more chances to appear at night or morning.

**Comment by PresidentEkhart** [comment]
Understood. Well we appreciate the effort you put into the maps!

Sent from my iPad

On Dec 22, 2019, at 2:41 PM, jeanropke <notifications@github.com> wrote:

﻿

Not possible. This events are random. Some gang hideouts has more chances to appear at night or morning.
