### ISSUE TITLE
Additional campfires

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDOMap#6]
See 

https://reddeadonlineclock.com/resources/RedDeadOnlineV2.pdf

for some additional campfire locations and other stuff.

Especially at Grangers farm and Flacos cabin.

**Comment by Shaftoe62** [comment]
Here are some coordinates:

More Campfires:

Flaco
lat: -29.921875
lng: 96.21875


Granger
lat: -69.6640625
lng: 110.1953125


Southfield Flats 
lat: -78.53125
lng: 127.8046875


Farm NE Mattock Pond
lat: -77.1796875
lng: 132.4140625

**Comment by jeanropke** [comment]
Added all missing campfires. Thanks.
