### ISSUE TITLE
Add toggles under gang hideouts to hide inactive hideouts

### ISSUE THREAD

**Issue by Senexis** [jeanropke/RDOMap#67]
> Might I suggest adding toggles under gang hideouts to hide inactive hideouts, display only inactive hideouts, or something along those lines? In case someone needs to know what hideouts will be active in the next few hours so they can plan ahead
- Sidzzz

When the hideout times are confirmed.

**Comment by skay8n** [comment]
Why would this be a recomendation for me

**Comment by colopopo** [comment]
Hop

**Comment by colopopo** [comment]
- > > Might I suggest adding toggles under gang hideouts to hide inactive hideouts, display only inactive hideouts, or something along those lines? In case someone needs to know what hideouts will be active in the next few hours so they can plan ahead
> 
> - Sidzzz
> 
> 
> 
> When the hideout times are confirmed.

**Comment by mongkut19** [comment]
D

**Comment by colopopo** [comment]
>

**Comment by colopopo** [comment]
shift u to

**Comment by colopopo** [comment]
D

**Comment by hjc7392** [comment]
처음이라 많이 배워야겧네요!

**Comment by tazzthespazz7** [comment]
> 처음이라 많이 배워야겧네요!

Same here .Just keep learning and get creative .
