### ISSUE TITLE
How to submit items?

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDOMap#7]
Hi guys,

You have certainly embarked on a herculaneum endeavor with this map!

There are still many things missing (items/locations).  How can we best submit those?

Something like:

Alaskan Ginseng, lat: -47.8203125, lng: 114.6796875
Alaskan Ginseng, lat: -47.671875, lng: 114.8125
Alaskan Ginseng, lat: -63.96875, lng: 100.8828125 

For items I suppose.

But what about the Heatmaps? I'm missing the 3 or 4 (or more) cougar spots around Roanoke Ridge for example.

**Comment by jeanropke** [comment]
If a plant is next to another one, don't need to add both.
Are this locations correct? If yes, I'll add on the map.

I used this image for cougars locations: 
https://img.rankedboost.com/wp-content/plugins/red-dead-redemption-2/assets/location-imgs/RDR2-Cougar-Locations.jpg

**Comment by Shaftoe62** [comment]
Ok, the coordinates are not very precise but there are Alaskan ginseng in these spots.

During the story I made a map for some plants when I wanted to craft 99 horsemeals and as much tonics. I have the photoshop document in layers but it's very big (170Mb). So I made a jpg with the plant names for the different colors. It's only for Ginseng, Golden Currant, Bay Bolete and Blackberry.
The center of the dots are pretty precise coordinates.
![RDR2plants](https://user-images.githubusercontent.com/53898212/67604748-b8350a80-f77c-11e9-8038-89dd08e635db.jpg)

**Comment by Shaftoe62** [comment]
I've added the spots where I regularly encounter cougars in Roanoke Ridge in magenta, and Panther spots in green.
![RDR2-Cougar-LocationsEdit](https://user-images.githubusercontent.com/53898212/67605505-d8fe5f80-f77e-11e9-874f-58e229f746a7.jpg)

**Comment by Shaftoe62** [comment]
> If a plant is next to another one, don't need to add both.
> Are this locations correct? If yes, I'll add on the map.
> 
> I used this image for cougars locations:
> https://img.rankedboost.com/wp-content/plugins/red-dead-redemption-2/assets/location-imgs/RDR2-Cougar-Locations.jpg

All locations are "groups" of plants. Sometimes there is 1, sometimes 3. But they are all distinct spots. Not different plants in a group.
