### ISSUE TITLE
Incorrect Gang Hideout Names

### ISSUE THREAD

**Issue by TJeffo** [jeanropke/RDOMap#74]
A couple of the gang hideouts have incorrect names.

Cholla Springs is actually named Rattlesnake Hollow.
Mossy Flats is actually named Fort Brennand.
Also Firewood Rise has been incorrectly spelled.

Hope I'm not being too picky, love the maps and they've helped me so much.
Thanks
![RattlesnakeHollow](https://user-images.githubusercontent.com/61903580/76141157-851f5380-6059-11ea-992a-719801a48461.jpg)

![FortBrennand](https://user-images.githubusercontent.com/61903580/76141195-d3345700-6059-11ea-8d01-23e8b1bc0748.jpg)

**Comment by Senexis** [comment]
All bar "Firwood" rise are the internal names for the hideouts. Changed them to make more sense like you suggested.
