### ISSUE TITLE
Grizzly Bear & Wolf

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDOMap#8]
Hi Jean,

Here some more predator spots. These are as precise as I dare to pinpoint them from my own experience.

It's not complete but these I can confirm for sure.

![predators-GrizzlyBear-Wolf](https://user-images.githubusercontent.com/53898212/67614591-e38d1900-f7bf-11e9-9b3c-01bdda455880.jpg)

**Comment by Shaftoe62** [comment]
The red areas are for GRIZZLY Bears. The dangerous ones. 

There are Black Bears in many other spots but these usually run away.

The heat map in the menu is now called "Bears". That should be "Grizzly Bears".

**Comment by jeanropke** [comment]
I'll use the names from RDR2 Guide. 
http://prntscr.com/pqo87a

**Comment by Shaftoe62** [comment]
Ok, fair enough. I believe in the game the pelts are also named "Perfect **Bear** Pelt" and "Perfect **Black Bear** Pelt".
