### ISSUE TITLE
Dog Encounter : Followed a dog to something interesting

### ISSUE THREAD

**Issue by WillBR41** [jeanropke/RDOMap#89]
Random dog event almost impossible to find because the dog appears only in one place on the map all day and at a certain time it is also almost impossible to find the random dog event if we do not know the exact location on the map that  the dog will appear.  It doesn't do much to have all locations if the dog will not show up in a certain place I have spent more than 7 hours in a solo session looking for the random dog first I went to all locations of the dog event then I stayed in a single location of the dog I stayed  day and night to see if it appears more unsuccessful I came to the conclusion that the dog is a random event that every day or a few hours the dog is appearing in a certain place on the map the solution and you inform in which location on the map the dog will appear  during the day could do that during the daily challenge day we need to find the dog would alert would help a lot

**Comment by Senexis** [comment]
I'll look into this next.

**Comment by WillBR41** [comment]
Ok thank you hopefully there is a solution.  I know that in one day in three different solo sessions I found the dog 3 times in the same place but on daily challenges day I only managed to find it once trying more than 7 hours after that day I never found it again when we really need to meet challenges  daily

**Comment by Senexis** [comment]
Won't be possible since it is synced through the host using a seed coming from the ROS. Nothing I can do.
